model:
  backbone: densenet121
  proj_layers: "128,relu,128,sigmoid"
  l_clst_coef: 0.8
  l_sep_coef: -0.08
  l_l1_coef: 1e-4
optim:
  warmup:
    proj_lr: 3e-3
    proj_weight_decay: 1e-3
    proto_lr: 3e-3
  joint:
    backbone_lr: 1e-4
    backbone_weight_decay: 1e-3
    proj_lr: 3e-3
    proj_weight_decay: 1e-3
    proto_lr: 3e-3
  final:
    start_epoch: 20
    fc_lr: 1e-4
