model:
  input_size: 224
  augmentation: False
  backbone: dinov2_vitb14_reg
  prototype_shape:
    - 2000
    - 128
    - 1
    - 1
  proj_layers: "128,relu,128,sigmoid"
  l_clst_coef: 0.8
  l_sep_coef: -0.08
  l_l1_coef: 1e-4
optim:
  joint_epoch_start:
    - 0
    - 30
  final_epoch_start:
    - 10
    - 40
  joint:
    proj_lr: 3e-3
    proj_weight_decay: 1e-3
    proto_lr: 3e-3
  final:
    fc_lr: 1e-4
  seed: 42
