model:
  name: dinov2_vits14_reg4
  tuning: block_expansion
  n_splits: 1
  gamma: 0.99
  n_prototypes: 5
  temperature: 0.2
  cls_head: sa
  sa_init: 0.5
  fg_extractor: "PCA"
  fg_extractor_args:
    compare_fn: "ge"
    threshold: 0.5
  losses:
    l_patch_coef: 0
    l_orth_coef: 0
    l_clst_coef: 0.8
    l_sep_coef: 0.08
    l_aux_coef: 0
  always_optimize_prototypes: false
dataset:
  augmentation: true
optim:
  optimizer: Adam
  epochs: 5
  backbone_lr: 0.0001
  cls_lr: 1.0e-06
  aux_lr: null
  lr_decay: null
  weight_decay: 0
  fine_tuning_epochs:
    - 1
    - 3
debug:
  epochs:
  - 0
  - 1
  - 2
  - 3
  - 4
seed: 42
