model:
  name: dinov2_vitb14_reg4
  tuning: block_expansion
  n_splits: 3
  gamma: 0.99
  n_prototypes: 5
  pooling_method: max
  temperature: 0.2
  cls_head: sa
  sa_init: 0.5
  fg_extractor: "PCA"
  fg_extractor_args:
    compare_fn: "le"
    threshold: 0.5
  losses:
    l_patch_coef: 0
    l_orth_coef: 0
    l_clst_coef: 0
    l_sep_coef: 0
  always_optimize_prototypes: false
dataset:
  augmentation: true
optim:
  epochs: 5
  backbone_lr: 0.005
  sa_lr: 1.0e-04
  cls_fc_lr: 1.0e-03
  scheduler: null
  fine_tuning_epochs:
    - 0
    - 1
    - 2
    - 3
    - 4
debug:
  epochs:
    - 0
    - 1
    - 2
    - 3
    - 4
seed: 42
